language: ruby

before_install:
  - gem install bundler
  - nvm install 13


rvm:
- 2.7.0

script:
 - bundle install --jobs=3 --retry=3
 - bundle exec rake db:create
 - bundle exec rake db:migrate
 - bundle exec rails webpacker:install
 - bundle exec rails webpacker:compile
 - bundle exec rake test
